name: Docker Compose Setup
description: Install Docker Compose

inputs:
  version:
    description: 'Compose release (example: v2.2.0)'
    required: false
    default: latest

runs:
  using: 'composite'
  steps:
    - name: setup requirements
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get -y install curl
        mkdir -p ~/.docker/cli-plugins/

    - name: download
      shell: bash
      run: |
        echo "Downloading Compose ${{ inputs.version }}"
        curl -SL https://github.com/docker/compose/releases/download/${{ inputs.version }}/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose

    - name: cleanup and verify
      shell: bash
      run: |
        chmod +x ~/.docker/cli-plugins/docker-compose
        docker compose version
